version: "3"
services:
  server:
    build:
      context: './server/'
      dockerfile: Dockerfile
    ports:
      - 5500:5500
    container_name: video-calling-server-container
    networks:
      - video-calling-project-network
    volumes:
      - ./server:/server
      - /server/node_modules
  client:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    container_name: video-calling-client-container
    networks:
      - video-calling-project-network
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - server
networks:
  video-calling-project-network:
